// Authenticaion
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const ONBOARDING = "ONBOARDING";

export const FRIENDS_LISTING = "FRIENDS_LISTING";
export const FRIENDS_LISTING_ERROR = "FRIENDS_LISTING_ERROR";

export const FETCH_FRIENDS_QUEUE_SETTINGS = "FETCH_FRIENDS_QUEUE_SETTINGS";
export const FETCH_FRIENDS_QUEUE_RECORDS = "FETCH_FRIENDS_QUEUE_RECORDS";
export const UPLOAD_FRIENDS_QUEUE_RECORDS_STEP_ONE =
	"UPLOAD_FRIENDS_QUEUE_RECORDS_STEP_ONE";
export const UPLOAD_FRIENDS_QUEUE_RECORDS_STEP_TWO =
	"UPLOAD_FRIENDS_QUEUE_RECORDS_STEP_TWO";
export const SAVED_FRIENDS_QUEUE_SETTINGS_RESPONSE =
	"SAVED_FRIENDS_QUEUE_SETTINGS_RESPONSE";
