
const
env = process.env,
appAuth = env.REACT_APP_AUTH,
appEnv = env.REACT_APP_ENV,
profileService = env.REACT_APP_PROFILE_SERVICE,
messageService = env.REACT_APP_MESSAGE_SERVICE,
campaignService = env.REACT_APP_CAMPAIGN_SERVICE

module.exports = {
    appUrl: process.env.REACT_APP_APP_URL,
    registerUrl: "https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/register",
    loginsUrl: "https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/login",
    forgetpasswordUrl: "https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/forget-password",
    resetpasswordUrl: "https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/reset-password",
    resetuserpasswordUrl: "https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/user-reset-password",
    mysettingSaveUrl: "https://"+process.env.REACT_APP_PROFILE_SERVICE+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/save-user-profile-settings",
    onboardingUrl:"https://"+process.env.REACT_APP_AUTH+".execute-api.us-east-1.amazonaws.com/"+process.env.REACT_APP_ENV+"/user-onbording-step-one",
    // // // resetuserpasswordUrl: "https://"+appAuth+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/user-reset-password",
    // Profile Service
    saveprofileDataUrl : "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/store-user-profile",
    fetchprofileDataUrl : "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-user-profiles",
    fetchprofileSettingUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-user-profile-settings",
    fetchFriendListUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-user-friendlist",
    whiteListFriend:"https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/user-whitelist-friend",
    blockListUserUrl:"https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/user-blacklist-friend",
    deleteFriend:"https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/user-delete-friend",
    fetchFriendLostUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-lost-friends",
    fetchSendFriendReqUrl:"https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-send-friend-request-log",
    fetchDiviceHistoryUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-device-information",
    fetchDeleteDiviceUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-device-information",
    storeDeviceInformationUrl : "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/store-device-information",
    fetchRequestSettingsUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-friend-request-settings",
    updateDefaultFriendRequestSettings: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/update-friend-request-send-default-settings",
    updateDeviceNameUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/update-device-information",
    deleteDeviceUrl: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-device-information",
    fetchAllPendingFrnds: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-pending-friend-request",
    deletePendingFrndsRequest: "https://"+profileService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-pending-friend-request-log",
    // Messages Service
    fetchDmfUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-dmfs",
    addUpdateDmfUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/store-dmf",
    addUpdateSubDmfUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/store-subdmf",
    deleteDmfUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-dmf",
    deleteSubDmfUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-subdmf",
    prioritySubDMF: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/update-subdmf-priority",
    fetchAllGroupMessagesUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-groups/all",
    fetchGroupByIdUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-group",
    // new message services
    fetchMessageGroupsUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-groups",
    createMessageGroupUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/create-group",
    deleteMessageGroupUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-group",
    addNewMessageGroupMessageUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/create-group-message",
    deleteMessageGroupMessageUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-group-message",
    // new segment message services
    createMessageSegmentUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/create-segment",
    fetchMessageSegmentsUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-segments",
    deleteMessageSegmentUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-segment",
    addNewMessageSegmentMessageUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/create-segment-message",
    deleteMessageSegmentMessageUrl: "https://"+messageService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-segment-message",
    // campaign services
    fetchAllCampaignsUrl: "https://"+campaignService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-user-campaigns?status=all",
    createCampaignUrl: "https://"+campaignService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/create-campaign",
    deleteCampaignUrl: "https://"+campaignService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/delete-campaign",
    updateCampaignStatusUrl: "https://"+campaignService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/update-campaign-status",
    addUsersToCampaignUrlUrl:`https://${campaignService}.execute-api.us-east-1.amazonaws.com/${appEnv}/add-friends-to-campaign`,
    fetchCampaignUrl: "https://"+campaignService+".execute-api.us-east-1.amazonaws.com/"+appEnv+"/fetch-campaign",
}
